### ISSUE TITLE
Known host file not configured, using user known host file: C:\Users\Sam/.ssh/known_hosts

### ISSUE THREAD

**Issue by MkJha** [stefanbirkner/fake-sftp-server-rule#13]
Error while trying to do sftp. 

Caused by: com.jcraft.jsch.JSchException: java.io.FileNotFoundException: C:\Users\Sam\.ssh\known_hosts (The system cannot find the path specified)
	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:57)
	at com.jcraft.jsch.JSch.setKnownHosts(JSch.java:317)
	at org.apache.camel.component.file.remote.SftpOperations.createSession(SftpOperations.java:286)
	at org.apache.camel.component.file.remote.SftpOperations.connect(SftpOperations.java:115)
	... 76 more

In actual sftp server it works fine , but on this mock , the connection could not get established

**Comment by stefanbirkner** [comment]
It looks like `C:\Users\Sam.ssh\known_hosts` is the wrong filename. I think `C:\Users\Sam\.ssh\known_hosts` is the correct filename.

**Comment by stefanbirkner** [comment]
IMO the problem is not related to Fake SFTP Server Rule. @MkJha where do you define the name of the `known_hosts` file?
