### ISSUE TITLE
ServiceConfigurationError when calling @Rule

### ISSUE THREAD

**Issue by stefanwendelmann** [stefanbirkner/fake-sftp-server-rule#17]
Hi Stefan,

i was integrating your nice test tool fake-sftp-server-rule in our code and saldy got an exception.

```java
  @Rule
  public final FakeSftpServerRule sftpServer = new FakeSftpServerRule().addUser("user", "pass");
```

```java
ftpUloadFileFromFilesystem(de.itout.spinterface.interfaces.fileDistributor.FileDistributorSFTPUploadTest)  Time elapsed: 1.084 sec  <<< ERROR!
java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider org.apache.sshd.client.subsystem.sftp.SftpFileSystemProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.nio.file.spi.FileSystemProvider.loadInstalledProviders(FileSystemProvider.java:119)
	at java.nio.file.spi.FileSystemProvider.access$000(FileSystemProvider.java:77)
	at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:169)
	at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:166)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.spi.FileSystemProvider.installedProviders(FileSystemProvider.java:166)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:324)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemBuilder.build(MemoryFileSystemBuilder.java:505)
	at com.github.stefanbirkner.fakesftpserver.rule.FakeSftpServerRule.createFileSystem(FakeSftpServerRule.java:421)
	at com.github.stefanbirkner.fakesftpserver.rule.FakeSftpServerRule.access$000(FakeSftpServerRule.java:158)
	at com.github.stefanbirkner.fakesftpserver.rule.FakeSftpServerRule$2.evaluate(FakeSftpServerRule.java:403)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassCastException: Cannot cast org.apache.sshd.common.util.security.bouncycastle.BouncyCastleSecurityProviderRegistrar to org.apache.sshd.common.util.security.SecurityProviderRegistrar
	at java.lang.Class.cast(Class.java:3369)
	at org.apache.sshd.common.util.threads.ThreadUtils.createDefaultInstance(ThreadUtils.java:114)
	at org.apache.sshd.common.util.threads.ThreadUtils.createDefaultInstance(ThreadUtils.java:121)
	at org.apache.sshd.common.util.threads.ThreadUtils.createDefaultInstance(ThreadUtils.java:107)
	at org.apache.sshd.common.util.security.SecurityUtils.register(SecurityUtils.java:397)
	at org.apache.sshd.common.util.security.SecurityUtils.isEDDSACurveSupported(SecurityUtils.java:529)
	at org.apache.sshd.common.signature.BuiltinSignatures$6.isSupported(BuiltinSignatures.java:103)
	at org.apache.sshd.common.NamedFactory.lambda$setUpBuiltinFactories$1(NamedFactory.java:63)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.sshd.common.NamedFactory.setUpBuiltinFactories(NamedFactory.java:64)
	at org.apache.sshd.common.BaseBuilder.setUpDefaultSignatures(BaseBuilder.java:339)
	at org.apache.sshd.common.BaseBuilder.fillWithDefaultValues(BaseBuilder.java:159)
	at org.apache.sshd.client.ClientBuilder.fillWithDefaultValues(ClientBuilder.java:103)
	at org.apache.sshd.client.ClientBuilder.fillWithDefaultValues(ClientBuilder.java:49)
	at org.apache.sshd.common.BaseBuilder.build(BaseBuilder.java:265)
	at org.apache.sshd.client.ClientBuilder.build(ClientBuilder.java:146)
	at org.apache.sshd.client.ClientBuilder.build(ClientBuilder.java:49)
	at org.apache.sshd.common.BaseBuilder.build(BaseBuilder.java:288)
	at org.apache.sshd.client.SshClient.setUpDefaultClient(SshClient.java:790)
	at org.apache.sshd.client.subsystem.sftp.SftpFileSystemProvider.<init>(SftpFileSystemProvider.java:157)
	at org.apache.sshd.client.subsystem.sftp.SftpFileSystemProvider.<init>(SftpFileSystemProvider.java:149)
	at org.apache.sshd.client.subsystem.sftp.SftpFileSystemProvider.<init>(SftpFileSystemProvider.java:135)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 39 more

```

**Comment by stefanwendelmann** [comment]
SOLVED: The Problem was two different bounycastle dependencies
