### ISSUE TITLE
Getting Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by dinnupega** [stefanbirkner/fake-sftp-server-rule#20]
Hi I am trying to integrate this fake-sftp-server-rule with my JUnits.

I started fake-sftp-server-rule and trying to make a connection with my client but I am facing below error.

> com.jcraft.jsch.JSchException: java.net.SocketException: Software caused connection abort: socket write error

	at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:315)
	at com.jcraft.jsch.Channel.connect(Channel.java:152)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)

[fakesftpserver.txt](https://github.com/stefanbirkner/fake-sftp-server-rule/files/5006106/fakesftpserver.txt)

Attached the sample code snippet, Can you please help me connecting to sftp server and make uploads and download.

Thanks in advance,
Dinesh

**Comment by stefanbirkner** [comment]
The test that you provided runs successfully on my machine. Can you show me the full stack trace of your error.
